// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq5xpPPW-vvqZKXrKzh9uBipQMNJ2ggZs',
    appId: '1:1040902206086:web:df6dd03887a3ead59f1707',
    messagingSenderId: '1040902206086',
    projectId: 'wave-fcdcf',
    authDomain: 'wave-fcdcf.firebaseapp.com',
    storageBucket: 'wave-fcdcf.firebasestorage.app',
    measurementId: 'G-T7P9PWDFXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNFvpzdffXzxydJeEisWC572kNW60Ua_Q',
    appId: '1:1040902206086:android:be8ee1c6534a03e49f1707',
    messagingSenderId: '1040902206086',
    projectId: 'wave-fcdcf',
    storageBucket: 'wave-fcdcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc_2CccjII_pFY9FbLl6pCjBFfg2sHhaM',
    appId: '1:1040902206086:ios:328d2b51c5ca65479f1707',
    messagingSenderId: '1040902206086',
    projectId: 'wave-fcdcf',
    storageBucket: 'wave-fcdcf.firebasestorage.app',
    iosClientId: '1040902206086-j4q9u4dsv638fg2adm8gc4q5gc8og80a.apps.googleusercontent.com',
    iosBundleId: 'com.fatouniang.wavefirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc_2CccjII_pFY9FbLl6pCjBFfg2sHhaM',
    appId: '1:1040902206086:ios:328d2b51c5ca65479f1707',
    messagingSenderId: '1040902206086',
    projectId: 'wave-fcdcf',
    storageBucket: 'wave-fcdcf.firebasestorage.app',
    iosClientId: '1040902206086-j4q9u4dsv638fg2adm8gc4q5gc8og80a.apps.googleusercontent.com',
    iosBundleId: 'com.fatouniang.wavefirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq5xpPPW-vvqZKXrKzh9uBipQMNJ2ggZs',
    appId: '1:1040902206086:web:25bca1e48c27c4269f1707',
    messagingSenderId: '1040902206086',
    projectId: 'wave-fcdcf',
    authDomain: 'wave-fcdcf.firebaseapp.com',
    storageBucket: 'wave-fcdcf.firebasestorage.app',
    measurementId: 'G-4GH83LR04X',
  );

}